"""Read-only steward prototype, generated by the existing dashboard pipeline.

No steward reporting API: registry + STATE/NOTES, estate_work's attention set,
and tracker observations. GitHub fills only references the tracker lacks.
"""
from __future__ import annotations

import html
import json
import re
import subprocess
import tomllib
from pathlib import Path
from urllib.parse import quote

import dashboard_nav
import dashboard_panels as panels
import estate_work
import steward_health

E = html.escape


def link(url, label):
    url = str(url or '')
    if not re.match(r'^https?://', url) and not url.startswith(('estate.html?', 'stewards.html?')):
        return E(str(label))
    return f'<a href="{E(url, quote=True)}">{E(str(label))}</a>'


def inline(text, *, link_refs=False):
    output, pos = [], 0
    pattern = r'\[([^\]]+)\]\((https?://[^\s)]+)\)|(https?://[^\s<>]+)'
    if link_refs:
        # Existing links/URLs match first, so their labels and targets stay intact.
        pattern += (r'|(?<![\w/.-])(?P<pr>(?:[A-Za-z0-9_.-]+/)?[A-Za-z0-9_.-]+#[0-9]+)\b'
                    r'|(?<![\w-])(?P<issue>[A-Z]+-[0-9]+)\b')
    for match in re.finditer(pattern, text):
        output.append(E(text[pos:match.start()]))
        if match.group(2):
            output.append(link(match.group(2), match.group(1)))
        elif link_refs and match.group('pr'):
            ref = match.group('pr')
            repo, number = ref.split('#')
            if '/' not in repo:
                output.append(E(ref))
                pos = match.end()
                continue
            output.append(link(f'https://github.com/{repo}/pull/{number}', ref))
        elif link_refs and match.group('issue'):
            ref = match.group('issue')
            output.append(E(ref))
        else:
            raw = match.group(3)
            url = raw.rstrip('.,;)')
            output.append(link(url, url) + E(raw[len(url):]))
        pos = match.end()
    output.append(E(text[pos:]))
    return ''.join(output)


def prose(text):
    """Small escape-first renderer for the headings, lists and tables in STATE.

    Raw HTML is always text; no Markdown extension can introduce an executable
    URL. Unrecognised Markdown remains readable verbatim.
    """
    output, table = [], False
    for line in text.splitlines():
        if line.startswith('|') and line.endswith('|'):
            if not table:
                output.append('<div class="table-scroll"><table>')
                table = True
            cells = line.strip('|').split('|')
            if all(re.fullmatch(r'[ :\-]+', c) for c in cells):
                continue
            output.append('<tr>' + ''.join('<td>' + inline(c.strip()) + '</td>' for c in cells) + '</tr>')
            continue
        if table:
            output.append('</table></div>')
            table = False
        heading = re.match(r'^#{1,6} (.*)', line)
        if heading:
            output.append('<h3>' + inline(heading.group(1)) + '</h3>')
        else:
            output.append('<div class="prose-line">' + inline(line or ' ') + '</div>')
    if table:
        output.append('</table></div>')
    return '<div class="steward-prose">' + ''.join(output) + '</div>'


def summary_table(headers, rows):
    def cells(values, tag):
        return '<tr>' + ''.join(f'<{tag}>' + inline(v, link_refs=True) + f'</{tag}>' for v in values) + '</tr>'
    return ('<div class="table-scroll"><table><thead>' + cells(headers, 'th')
            + '</thead><tbody>' + ''.join(cells(r, 'td') for r in rows)
            + '</tbody></table></div>')


def table_cells(line):
    return [cell.strip().replace(r'\|', '|')
            for cell in re.split(r'(?<!\\)\|', line.strip().strip('|'))]


def state_tables(text):
    """Extract summaries only; the original STATE rendering stays intact."""
    # Template comments and fenced examples are not current state entries.
    text = re.sub(r'<!--.*?-->', '', text, flags=re.S)
    lines, fence = [], None
    for line in text.splitlines():
        marker = re.match(r'^\s*(`{3,}|~{3,})', line)
        if marker:
            if fence is None:
                fence = marker.group(1)
            elif marker.group(1)[0] == fence[0] and len(marker.group(1)) >= len(fence):
                fence = None
            continue
        if fence is None:
            lines.append(line)
    output, section, links = [], '', []
    i = 0
    while i < len(lines):
        line = lines[i].strip()
        heading = re.match(r'^#{1,2}\s+(.+?)(?:\s+#+)?$', line)
        if heading:
            section = heading.group(1)
        if section.casefold() == 'links and artifacts':
            entry = re.match(r'^[-*+]\s+(.+)', line)
            if entry:
                value = entry.group(1)
                labeled = re.match(r'^(.*?):\s+(.*)$', value)
                if labeled:
                    links.append([labeled.group(1), labeled.group(2)])
                else:
                    markdown_link = re.fullmatch(r'\[([^]]+)\]\((https?://[^\s)]+)\)', value)
                    if markdown_link:
                        links.append([markdown_link.group(1), value])
        if '|' in line and i + 1 < len(lines):
            headers = table_cells(line)
            separator = table_cells(lines[i + 1])
            if (len(headers) == len(separator) and len(headers) > 1
                    and all(re.fullmatch(r':?-{3,}:?', c) for c in separator)):
                rows = []
                i += 2
                while i < len(lines) and '|' in lines[i] and lines[i].strip():
                    cells = table_cells(lines[i])
                    if len(cells) != len(headers):
                        break
                    rows.append(cells)
                    i += 1
                if rows and any(re.search(r'\b(tickets?|prs?|pull requests?)\b', h, re.I) for h in [section, *headers]):
                    output.append(('Tickets / PRs' if not section else section, summary_table(headers, rows)))
                continue
        i += 1
    if links:
        output.insert(0, ('Links and artifacts', summary_table(['What it is', 'Link'], links)))
    return output


def project_links(row, projects):
    """Names come from the registry or focus config, never from slug guessing."""
    if row.get('projects'):
        return row['projects']
    epic = row.get('epic') or {}
    if epic.get('kind') != 'linear-project':
        return []
    canonical = lambda url: str(url or '').rstrip('/').removesuffix('/overview')
    for project in projects.values():
        if epic.get('url') and canonical(project.get('url')) == canonical(epic['url']):
            return [dict(project, url=epic['url'])]
    return [{'name': epic.get('name') or 'Name unavailable', 'url': epic.get('url')}]


def read_file(path, now):
    try:
        text = path.read_text(encoding='utf-8')
        stamp = path.stat().st_mtime
        outcome, why = panels.OUT_OK, None
    except (OSError, UnicodeError) as exc:
        text, stamp = '', None
        outcome = panels.OUT_NO_STATE if isinstance(exc, FileNotFoundError) else panels.OUT_UNREADABLE
        why = str(exc)
    return text, panels.envelope('steward-file', str(path), outcome,
                                now=now, as_of=stamp, why=why)


def references(text, repos):
    found = set()
    for repo in repos:
        short = repo.rsplit('/', 1)[-1]
        for pattern in (rf'(?<![\w/-])(?:{re.escape(repo)}|{re.escape(short)})#(\d+)\b',
                        rf'https://github\.com/{re.escape(repo)}/pull/(\d+)\b'):
            found.update(f'{repo}#{n}' for n in re.findall(pattern, text))
    return found


def related(task, row):
    needles = [row.get('task'), row.get('slug'), (row.get('epic') or {}).get('ref')]
    text = json.dumps(task, ensure_ascii=False)
    return any(re.search(r'(?<![\w-])' + re.escape(n) + r'(?![\w-])', text, re.I)
               for n in needles if isinstance(n, str) and n)


def github_repo(repo):
    try:
        result = subprocess.run(
            ['gh', 'pr', 'list', '--repo', repo, '--state', 'open', '--limit', '200',
             '--json', 'number,title,url,state,isDraft,updatedAt,headRefName'],
            capture_output=True, text=True, timeout=10)
        if result.returncode:
            raise ValueError((result.stderr or 'GitHub request failed')[:240])
        rows = json.loads(result.stdout)
        if not isinstance(rows, list) or not all(isinstance(p, dict) and 'number' in p for p in rows):
            raise ValueError('GitHub returned invalid PR rows')
        return rows, None
    except (OSError, subprocess.SubprocessError, ValueError) as exc:
        return None, str(exc)


def gather(state: Path, work: dict, now: float):
    entries, registry_read = steward_health.load_registry(str(state / 'stewards'))
    tracker, tracker_outcome, tracker_why = panels.read_producer_json(state / 'pr-tracker/state.json')
    tracked = (tracker or {}).get('entries') if isinstance(tracker, dict) else None
    if not isinstance(tracked, dict):
        tracked = {}
        if tracker_outcome == panels.OUT_OK:
            tracker_outcome, tracker_why = panels.OUT_UNREADABLE, 'tracker entries are not an object'
    try:
        with (state / 'focus/projects.toml').open('rb') as source:
            projects = tomllib.load(source).get('projects', {})
    except (OSError, ValueError):
        projects = {}
    cache = {}
    result = {'registry': registry_read, 'rows': [], 'generated_epoch': now}
    tasks = {t['id']: t for t in work.get('tasks', [])}
    selected = set(work.get('attention', [])) | set(work.get('proposals', []))
    for entry in entries:
        row = entry['row'] or {'slug': entry['slug']}
        slug = row.get('slug', '')
        if not isinstance(slug, str) or not re.fullmatch(r'[a-z0-9][a-z0-9-]*', slug):
            continue
        item = {'row': row, 'error': entry['error'], 'prs': [], 'pr_readings': [], 'attention': []}
        item['projects'] = project_links(row, projects)
        tree = row.get('worktree')
        for name in ('STATE', 'NOTES'):
            path = Path(tree) / 'project' / f'{name}.md' if tree else state / 'stewards' / slug / f'{name}.md'
            item[name], item[name + '_reading'] = read_file(path, now)
        repos = [r for r in row.get('repos', []) if isinstance(r, str) and re.fullmatch(r'[\w.-]+/[\w.-]+', r)]
        wanted = references(item['STATE'], repos)
        # Select only explicit current-state PR references or epic identifiers;
        # repo membership alone would label unrelated work as part of this epic.
        epic = (row.get('epic') or {}).get('ref')
        for key, observation in tracked.items():
            if not isinstance(observation, dict):
                continue
            pr = observation.get('pr') or {}
            if pr.get('repo') in repos and epic and related(pr, {'epic': {'ref': epic}}):
                wanted.add(key)
        for repo in repos:
            keys = sorted(k for k in wanted if k.startswith(repo + '#'))
            missing = [k for k in keys if k not in tracked]
            if missing:
                if repo not in cache:
                    cache[repo] = github_repo(repo)
                fetched, error = cache[repo]
                item['pr_readings'].append(panels.envelope(
                    'pr_board', f'GitHub open PRs: {repo}', panels.OUT_ERROR if error else panels.OUT_OK,
                    now=now, as_of=now, partial=bool(fetched and len(fetched) >= 200), why=error))
                by_number = {str(p['number']): p for p in fetched or []}
                for key in missing:
                    pr = by_number.get(key.split('#')[1])
                    item['prs'].append({'key': key, 'pr': pr or {'url': f'https://github.com/{repo}/pull/{key.split("#")[1]}'},
                                        'label': 'open · GitHub' if pr else 'open status unconfirmed; not returned by this read'})
            for key in keys:
                obs = tracked.get(key)
                if not isinstance(obs, dict):
                    continue
                pr = obs.get('pr') or {}
                if pr.get('state') in ('MERGED', 'CLOSED'):
                    continue
                stamp = obs.get('last_successful_observation_at')
                item['prs'].append({'key': key, 'pr': pr,
                                    'label': f'{pr.get("state", "unknown")} · tracker · {stamp or "observation time unknown"}'})
                item['pr_readings'].append(panels.envelope('pr_board', key, tracker_outcome,
                    now=now, as_of=stamp, why=tracker_why,
                    partial=bool(obs.get('exit_refused') or obs.get('observation'))))
        if tracker_outcome != panels.OUT_OK:
            item['pr_readings'].append(panels.envelope('pr_board', 'PR tracker', tracker_outcome, now=now, why=tracker_why))
        item['attention'] = [tasks[k] for k in selected if k in tasks and related(tasks[k], row)
                             and tasks[k].get('status') not in estate_work.TERMINAL]
        item['attention'].sort(key=lambda t: t['id'])
        result['rows'].append(item)
    return result


def render_item(dashboard, item, work):
    row = item['row']
    title = E(str(row.get('title') or row['slug']))
    body = f'<h1>{title}</h1><p>Registry: {E(str(row.get("status", "unknown")))} · '
    projects = item.get('projects', project_links(row, {}))
    if projects:
        body += ' · '.join(('Project: ' if i == 0 else 'Related project: ')
                           + link(p.get('url'), p.get('name') or 'Name unavailable')
                           for i, p in enumerate(projects))
    else:
        body += link((row.get('epic') or {}).get('url'), (row.get('epic') or {}).get('ref', 'Epic'))
    if row.get('task'):
        body += ' · ' + link('estate.html?task=' + quote(row['task']), row['task'])
    body += '</p>'
    if item['error']:
        body += '<p class="error">Registry unavailable: ' + E(item['error']) + '</p>'
    for heading, table in state_tables(item['STATE']):
        body += '<section><h2>' + E(heading) + '</h2>'
        body += dashboard.render_panel_state(item['STATE_reading']) + table + '</section>'
    body += '<section><h2>Current status, artifacts and decisions</h2>'
    body += dashboard.render_panel_state(item['STATE_reading']) + prose(item['STATE']) + '</section>'
    body += '<section><h2>Related estate attention and proposals</h2>'
    body += dashboard.render_panel_state(work.get('reading'))
    for task in item['attention']:
        body += '<article><h3>' + link('estate.html?task=' + quote(task['id']), task['id'] + ' · ' + task['title']) + '</h3>'
        surface = estate_work.decision_surface(task)
        body += '<p>' + E(str(task.get('classification') or surface.get('classification') or 'no classification recorded')) + ' · ' + E(task['status']) + '</p>'
        for key in ('question', 'recommendation', 'context_line'):
            value = task.get(key) or surface.get(key)
            if value:
                body += prose(f'{key.replace("_", " ")}: {value}')
        body += '</article>'
    if not item['attention']:
        body += '<p>No linked rows found in the estate snapshot; decisions in STATE.md may not have separate estate filings.</p>' if work.get('available') else '<p>Estate attention unavailable; no absence can be concluded.</p>'
    body += '</section><section><h2>Related open PRs</h2><p>Matched by current STATE.md references or epic identifier. This is not a complete repository inventory.</p>'
    for env in item['pr_readings']:
        body += dashboard.render_panel_state(env)
    for p in item['prs']:
        body += '<article>' + link(p['pr'].get('url'), p['key'] + ' ' + p['pr'].get('title', '')) + '<p>' + E(p['label']) + '</p></article>'
    if not item['prs']:
        body += '<p>No matching PR observations available. Check the current-state notes and epic for additional scope.</p>'
    body += '</section><section><h2>Steward history</h2><p>Durable NOTES.md record, newest entry first; this does not prove Slack delivery.</p>'
    body += dashboard.render_panel_state(item['NOTES_reading'])
    parts = re.split(r'(?=^## )', item['NOTES'], flags=re.M)
    if len(parts) > 1:
        body += ''.join(prose(p) for p in reversed(parts[1:]))
        body += '<details><summary>Notes preamble</summary>' + prose(parts[0]) + '</details>'
    else:
        body += prose(item['NOTES'])
    return body + '</section>'


def payload(dashboard, snapshot):
    model = snapshot.get('stewards', {'rows': [], 'registry': {}})
    directory = '<h1>Stewards</h1><p>Current status and durable history for each registered steward.</p>'
    if model['registry'].get('warrant') != 'observed':
        directory += '<p class="error">Registry unavailable: ' + E(str(model['registry'].get('why', 'not read'))) + '</p>'
    pages = {}
    for item in model['rows']:
        row = item['row']
        slug = row['slug']
        directory += '<article><h2>' + link('stewards.html?steward=' + quote(slug), row.get('title') or slug) + '</h2><p>' + E(str(row.get('status', 'unknown'))) + '</p></article>'
        pages[slug] = render_item(dashboard, item, snapshot.get('estate_activity', {}))
    if not pages and model['registry'].get('warrant') == 'observed':
        directory += '<p>No registered stewards.</p>'
    return {'generated_at': snapshot.get('generated_at'), 'generated_epoch': snapshot.get('generated_epoch'),
            'directory': directory, 'pages': pages}


def render(dashboard, snapshot):
    name = E(f'{snapshot.get("estate", "")} / {snapshot.get("operator", "")}'.strip(' /'))
    return '''<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>Stewards · estate dashboard</title>
<style>''' + dashboard.CSS + '''
.stewards-main section,.stewards-main article{background:var(--surface);border:1px solid var(--edge);padding:18px;margin:16px 0;border-radius:8px}
.steward-prose{overflow-wrap:anywhere;font-family:inherit;line-height:1.6;margin:12px 0}.stewards-main a{color:var(--accent)}.error{color:var(--crit)}h2{margin-bottom:12px}.prose-line{white-space:pre-wrap;min-height:.7em}.table-scroll{overflow-x:auto}td,th{padding:8px;text-align:left;border-bottom:1px solid var(--edge)}
.stewards-crumb{font-size:11px;color:var(--info)}.stewards-crumb[hidden]{display:none}
</style></head><body><div class="wrap">''' + dashboard_nav.render("stewards") + '''
<header class="masthead"><div class="brand"><div class="eyebrow">Epic stewards</div>
<div class="title">''' + name + '''</div>
<div class="subline"><span id="refresh" class="refresh" role="status">Loading steward snapshot…</span>
<a class="stewards-crumb" id="stewards-crumb" href="/stewards.html" hidden>← All stewards</a></div></div></header>
<main id="stewards" class="stewards-main"></main></div>
<script>''' + dashboard.JS + '''</script>
<script>
const slug=new URLSearchParams(location.search).get('steward');
if(slug)document.getElementById('stewards-crumb').hidden=false;
let previous='';
async function refresh(){try{
 const r=await fetch('stewards.json',{cache:'no-store'});if(!r.ok)throw Error('HTTP '+r.status);
 const d=await r.json();const body=slug?(Object.hasOwn(d.pages,slug)?d.pages[slug]:null):d.directory;
 if(body!==previous){document.getElementById('stewards').innerHTML=body||'<h1>Steward unavailable</h1><p>This slug is not in the generated registry.</p>';previous=body;}
 const old=Date.now()/1000-d.generated_epoch>300;
 const label=document.getElementById('refresh');label.className='refresh'+(old?' error':'');
 label.textContent=(old?'Snapshot stale · ':'Updated · ')+d.generated_at;
}catch(e){const label=document.getElementById('refresh');label.className='refresh error';label.textContent='Refresh failed; displayed content may be old: '+e.message;}}
refresh();setInterval(refresh,30000);
</script></body></html>'''
